

spring.application.name=Cert-verification-system

# ========================
# Database Configuration
# ========================
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/Certichain_system?createDatabaseIfNotExist=true}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:Dipak$$$123**}

# ========================
# JPA / Hibernate
# ========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=${JPA_SHOW_SQL:false}

# ========================
# Logging
# ========================
logging.file.name=logs/cert-verification.log
logging.level.com.devSoft=${LOG_LEVEL:INFO}

# ========================
# Mail (SMTP)
# ========================
spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME:dipaknicyer@gmail.com}
spring.mail.password=${MAIL_PASSWORD:ketyezyeiqbjwrvm}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
spring.mail.properties.mail.smtp.starttls.enable=true

# ========================
# File Upload
# ========================
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
